AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  S3BucketName:
    Type: String
    Description: S3 bucket which will be used by the website

  DomainName:
    Type: String
    Description: Domain to host the website in

  AcmArn:
    Type: String
    Description: Certificate ARN for the website
  

Resources:
  LambdaHandlers:
    Type: AWS::Serverless::Application
    Properties:
      Location: lambda-api.yml
      Parameters:
        S3BucketName: !Ref S3BucketName

  S3CloudFront:
    Type: AWS::Serverless::Application
    Properties:
      Location: s3-cloudfront.yml
      Parameters:
        S3BucketName: !Ref S3BucketName
        DomainName: !Ref DomainName
        AcmArn: !Ref AcmArn

  Cognito:
    Type: AWS::Serverless::Application
    Properties:
      Location: cognito.yml
