version = 0.1

[cloud]
[cloud.deploy]
[cloud.deploy.parameters]
stack_name="vkloud"
s3_prefix="vkloud"
region="us-east-1"
confirm_changeset=false
capabilities="CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
tags="info:owner=derp"
parameter_overrides=[
    "S3BucketName=vkaramoutas-cloud-project",
    "DomainName=vkaramoutas.xyz",
    "AcmArn=arn:aws:acm:us-east-1:767397699663:certificate/6be6f058-f9bf-4582-991e-78ad96262694",
    "SesArn=arn:aws:ses:us-east-1:767397699663:identity/vkaramoutas.xyz"
]
