name: Deploy VKloud Infrastructure

on:
  workflow_dispatch:

env:
  AWS_ROLE_ARN: arn:aws:iam::767397699663:role/VKloudOIDCRole-Role-JJn3ijaLTzAO
  AWS_ARTIFACTS_BUCKET: vkloud-artifacts
  TEMPLATE_PATH: CloudFormation/main.yml
  REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Build Stack
        run: sam build -t ${{ env.TEMPLATE_PATH }} --use-container

      - name: Deploy Stack
        run: |
          sam deploy \
            --no-fail-on-empty-changeset \
            --config-env cloud \
            --s3-bucket ${{ env.AWS_ARTIFACTS_BUCKET }} \
            --template-file ${{ env.TEMPLATE_PATH }} \
            --config-file samconfig.toml
