name: Deploy VKloud Frontend

on:
  workflow_dispatch:

env:
  AWS_S3_BUCKET: vkaramoutas-cloud-project
  AWS_IAM_ROLE_ARN: arn:aws:iam::767397699663:role/VKloudOIDCRole-Role-JJn3ijaLTzAO

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies & build
        run: |
          cd Frontend
          yarn install
          yarn build
      - name: Configure AWS credentials with OIDC
        id: login-aws
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_IAM_ROLE_ARN }}
          role-session-name: build-${{ github.sha }}
          aws-region: us-east-1
      - name: Deploy to S3
        run: |
          aws s3 sync Frontend/dist/ s3://${{ env.AWS_S3_BUCKET }}
